### ISSUE TITLE
Application works on Ubuntu, but errors on MAC & WINDOWS

### ISSUE THREAD

**Issue by openspacetech** [zeit/pkg#111]
My application uses socket.io. I created the package using `pkg .`

During packaging, i got below warning 
```
Warning Cannot include native addon into executable.
  /apps/pinger/web/node_modules/raw-socket/build/Release/raw.node
  The addon file must be distributed with executable.
```
After the package is created, I got 3 executables create (one each for Linux, Windows, MacOS).

Executable works great on Linux (Ubuntu 14.04). But fails to run on Windows & MacOS. I get below error.
```
buffer.js:821
    throw new RangeError('Index out of range');
          ^

RangeError: Index out of range
    at checkOffset (buffer.js:821:11)
    at Buffer.readInt16LE (buffer.js:956:5)
    at evalmachine.<anonymous>:0
    at Object.Module._extensions..node (evalmachine.<anonymous>:0)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.require (evalmachine.<anonymous>:0)
    at require (internal/module.js:20:19)
```

**Comment by igorklopov** [comment]
Hi! Please read https://github.com/zeit/pkg/issues/104
