### ISSUE TITLE
Can't load native add-ons

### ISSUE THREAD

**Issue by jviotti** [zeit/pkg#117]
From https://github.com/zeit/pkg/issues/116

I'm getting the following error when trying to run the Etcher CLI:

```
Error: Could not locate the bindings file. Tried:
 → /snapshot/Users/jviotti/Projects/resin/etcher/node_modules/mountutils/build/MountUtils.node
 → /snapshot/Users/jviotti/Projects/resin/etcher/node_modules/mountutils/build/Debug/MountUtils.node
 → /snapshot/Users/jviotti/Projects/resin/etcher/node_modules/mountutils/build/Release/MountUtils.node
 → /snapshot/Users/jviotti/Projects/resin/etcher/node_modules/mountutils/out/Debug/MountUtils.node
 → /snapshot/Users/jviotti/Projects/resin/etcher/node_modules/mountutils/Debug/MountUtils.node
 → /snapshot/Users/jviotti/Projects/resin/etcher/node_modules/mountutils/out/Release/MountUtils.node
 → /snapshot/Users/jviotti/Projects/resin/etcher/node_modules/mountutils/Release/MountUtils.node
 → /snapshot/Users/jviotti/Projects/resin/etcher/node_modules/mountutils/build/default/MountUtils.node
 → /snapshot/Users/jviotti/Projects/resin/etcher/node_modules/mountutils/compiled/6.10.0/darwin/x64/MountUtils.node
    at bindings (/snapshot/Users/jviotti/Projects/resin/etcher/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/snapshot/Users/jviotti/Projects/resin/etcher/node_modules/mountutils/index.js:52:37)
    at Module._compile (module.js:570:32)
    at Module._compile (evalmachine.<anonymous>:0)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.require (evalmachine.<anonymous>:0)
    at require (internal/module.js:20:19)
    at Object.console./snapshot/Users/jviotti/Projects/resin/etcher/lib/cli/writer.js.dev (evalmachine.<anonymous>:0)
    at Module._compile (evalmachine.<anonymous>:0)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.require (evalmachine.<anonymous>:0)
    at require (internal/module.js:20:19)
    at Object.console./snapshot/Users/jviotti/Projects/resin/etcher/lib/cli/etcher.js.dev (evalmachine.<anonymous>:0)
    at Module._compile (evalmachine.<anonymous>:0)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (evalmachine.<anonymous>:0)
    at run (bootstrap_node.js:398:7)
    at startup (bootstrap_node.js:153:9)
    at bootstrap_node.js:513:3
```

However the third path does exist:

```
$ file node_modules/mountutils/build/Release/MountUtils.node
node_modules/mountutils/build/Release/MountUtils.node: Mach-O 64-bit bundle x86_64
```

How to reproduce:

```sh
git clone https://github.com/resin-io/etcher
cd etcher
pkg --output etcher -t node6-macos-x64 lib/cli/etcher.js
./etcher
```

Is there something else that needs be done for add-ons to be included in the snapshot?

**Comment by igorklopov** [comment]
Fix is available in pkg@4
