### ISSUE TITLE
innerError TypeError: Cannot read property '1' of null

### ISSUE THREAD

**Issue by Kenhuey** [zeit/pkg#1342]
What should I do...
Please help.
```
[2021-10-21 20:43:13] [ERROR] <10_0_12_11 8792> console - innerError TypeError: Cannot read property '1' of null
    at process.dlopen (pkg/prelude/bootstrap.js:2071:69)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1131:18)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at Module.require (pkg/prelude/bootstrap.js:1719:31)
    at require (internal/modules/cjs/helpers.js:92:18)
    at new WindowsPtyAgent (C:\snapshot\myproject1\node_modules\node-pty\lib\windowsPtyAgent.js:57:40)
    at new WindowsTerminal (C:\snapshot\myproject1\node_modules\node-pty\lib\windowsTerminal.js:50:24)
    at spawn (C:\snapshot\myproject1\node_modules\node-pty\lib\index.js:28:12)
```

**Comment by lancety** [comment]
see this https://github.com/vercel/pkg/discussions/1623#discussioncomment-2729625 @Kenhuey
