### ISSUE TITLE
line number of call stack

### ISSUE THREAD

**Issue by bill0119** [zeit/pkg#142]
test.js 
```
var test = 123;

console.trace();

console.trace();
```

run node

```
D:\>node test.js
Trace
    at Object.<anonymous> (D:\test.js:3:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
Trace
    at Object.<anonymous> (D:\test.js:5:9)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```
We can find out test.js line number is 3 and 5.

run pkg
```
D:\>pkg test.js -o test.bin
> pkg@4.1.0
> Targets not specified. Assuming:
  node7-win-x64

D:\>test.bin
Trace
    at Object.<anonymous> (D:\snapshot\test.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1136:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (pkg/prelude/bootstrap.js:1192:12)
    at run (bootstrap_node.js:469:7)
    at startup (bootstrap_node.js:193:9)
    at bootstrap_node.js:584:3
Trace
    at Object.<anonymous> (D:\snapshot\test.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1136:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (pkg/prelude/bootstrap.js:1192:12)
    at run (bootstrap_node.js:469:7)
    at startup (bootstrap_node.js:193:9)
    at bootstrap_node.js:584:3
```
Line number of test.js can't be display.
Is any way to get line number of call stack?

**Comment by mika-fischer** [comment]
@bill0119 This is happening because pkg does not include the sources in the executable by default. You can circumvent this by setting `private` to `false` and `license` to `MIT` in `package.json`.

It would be nice if this was overridable directly without messing with `package.json`.

**Comment by igorklopov** [comment]
@mika-fischer 👍

**Comment by igorklopov** [comment]
Pass `--public` option to pkg. It is yet experimental feature. It takes sources of top-level project into executable to make it show full stack traces at run time.
