### ISSUE TITLE
Error phantomjs

### ISSUE THREAD

**Issue by ston3o** [zeit/pkg#147]
Hello,

I have a problem to use pkg with phantomjs.

```bash
node --version # v8.0.0
```

```javascript
// index.js
const phantom = require('phantom'); // v4.0.4

(async function() {
    const instance = await phantom.create();
    await instance.exit();
}());
```

```
$ pkg index.js -t node8-linux
$ ./index

error: Could not spawn [/snapshot/test/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs] executable. Please make sure phantomjs is installed correctly.
error:  Error: spawn /snapshot/test/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1193:13)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
```

**Comment by igorklopov** [comment]
`phantomjs` is supported in pkg@4.2.0. Please upgrade!

**Comment by BernsteinA** [comment]
@igorklopov should this work for phantomjs-prebuilt too?

**Comment by igorklopov** [comment]
I suppose yes.

**Comment by BernsteinA** [comment]
@igorklopov should I open a new issue?

**Comment by igorklopov** [comment]
No, since we are about same product, just go on here :)

**Comment by BernsteinA** [comment]
wait never mind it was partly my fault.
pkg said
```
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  [projectpath]/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
  path-to-executable/phantom/phantomjs
```
That file didn't exist, so I copied over `[projectpath]/bin/phantomjs`, assuming that was correct, when it turns out that I actually needed `/usr/local/lib/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs`

**Comment by ston3o** [comment]
Sorry but I still have the same error :(

**Comment by igorklopov** [comment]
Please post full error info. Also ensure you have pkg@4.2.1.

**Comment by ston3o** [comment]
```bash
node --version # v8.2.1
npm --version # 5.3.0
pkg --version # 4.2.1
```

```node
// index.js
const phantom = require('phantom'); // v4.0.5

(async function() {
    const instance = await phantom.create();
    await instance.exit();
}());

```

```bash
pkg index.js -t node8-linux                                                                                                                                                                         
> pkg@4.2.1                                                                                                                                                                                                                        
> Warning Cannot include file %1 into executable.                                                                                                                                                                                  
  The file must be distributed with executable as %2.                                                                                                                                                                              
  /tmp/pkg/node_modules/phantom/lib/shim/index.js                                                                                                                                                                                  
  path-to-executable/phantom/index.js                                                                                                                                                                                              
> Warning Cannot include file %1 into executable.                                                                                                                                                                                  
  The file must be distributed with executable as %2.
  /tmp/pkg/node_modules/phantom/lib/shim/function_bind_polyfill.js
  path-to-executable/phantom/function_bind_polyfill.js
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.
  /tmp/pkg/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
  path-to-executable/phantom/phantomjs
> Warning Cannot include file %1 into executable.
  The file must be distributed with executable as %2.                                                                                                                                                                              
  /tmp/pkg/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs.exe                                                                                                                                                           
  path-to-executable/phantom/phantomjs.exe
```

```bash
./index                                                                                                                                                                                             
error: Could not spawn [/tmp/pkg/phantom/phantomjs] executable. Please make sure phantomjs is installed correctly.                                                                                                                 
error:  Error: spawn /tmp/pkg/phantom/phantomjs ENOENT                                                                                                                                                                             
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1281:13)
    at startup (bootstrap_node.js:200:16)
    at bootstrap_node.js:617:3
```

**Comment by igorklopov** [comment]
Did you follow all warnings? :) Please `ls` of your directory where `index` executable is run from.

**Comment by ston3o** [comment]
```bash
$ ls -la /tmp/pkg                                                                                                                                                                                     
total 41660                                                                                                                                                                                                                        
drwxr-xr-x   4 ston3o users      120 Aug  4 18:08 .                                                                                                                                                                                
drwxrwxrwt  25 root   root      1720 Aug  4 18:06 ..
drwxr-xr-x 100 ston3o users     2000 Aug  4 17:32 node_modules
drwxr-xr-x   2 ston3o users      100 Aug  4 18:08 phantom
-rwxr-xr-x   1 ston3o users 42653326 Aug  4 18:08 index
-rw-r--r--   1 ston3o users      145 Aug  4 17:26 index.js
```

My bad, it's works if I copy files provided by warnings.

Thanks !

**Comment by iqqmuT** [comment]
```
$ node --version
v8.7.0
$ npm --version
5.4.2
$ pkg --version
4.3.1
```
I tried to do the same as @ston3o but I get following error:
```
$ ./index 
error: Can't open '/snapshot/pkg/node_modules/phantom/lib/shim/index.js'
```
I don't understand where I should copy `node_modules/phantom/lib/shim/function_bind_polyfill.js`, since it is not included in `phantom` package. However, it does not seem to be the problem. I have copied `index.js` and `phantomjs` to the right place:
```
$ tree -I node_modules                
.
├── index
├── index.js
├── package-lock.json
└── phantom
    ├── index.js
    └── phantomjs

1 directory, 5 files
```

**Comment by iqqmuT** [comment]
Seems that this error occurs when I'm using phantom>=4.0.6. phantom@4.0.5 works ok. Also `node_modules/phantom/lib/shim/function_bind_polyfill.js` was removed in version 4.0.6.
