### ISSUE TITLE
`node4-linux` binary fails without accompanying node_modules directory

### ISSUE THREAD

**Issue by treefort** [zeit/pkg#153]
After using pkg v4.1.1 to compile a binary with a target of `node4-linux` with the following command:

```
# pkg -t node4-linux index.js -o mybinary
> pkg@4.1.1
> Fetching base Node.js binaries to: ~/.pkg-cache
  fetched-v4.8.3-linux-x64     [====================] 100%
> Warning Cannot resolve 'path.resolve(directory, file)'
  /home/customer/myproject/node_modules/prompt/node_modules/utile/lib/index.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
> Warning Cannot resolve 'path.resolve(directory, file)'
  /home/customer/myproject/node_modules/prompt/node_modules/utile/lib/index.js
  Use a string literal as argument for 'require', or leave it
  as is and specify the resolved file name in 'scripts' option.
```

The resulting binary will run, but only if it is in the same directory with `node_modules.` If the binary is placed in any other directory, I get the following errors:
```
pkg/prelude/bootstrap.js:1080
      throw error;
      ^

Error: Could not locate the bindings file. Tried:
 → /snapshot/myproject/node_modules/serialport/build/serialport.node
 → /snapshot/myproject/node_modules/serialport/build/Debug/serialport.node
 → /snapshot/myproject/node_modules/serialport/build/Release/serialport.node
 → /snapshot/myproject/node_modules/serialport/out/Debug/serialport.node
 → /snapshot/myproject/node_modules/serialport/Debug/serialport.node
 → /snapshot/myproject/node_modules/serialport/out/Release/serialport.node
 → /snapshot/myproject/node_modules/serialport/Release/serialport.node
 → /snapshot/myproject/node_modules/serialport/build/default/serialport.node
 → /snapshot/myproject/node_modules/serialport/compiled/4.8.3/linux/x64/serialport.node
    at bindings (/snapshot/myproject/node_modules/serialport/node_modules/bindings/bindings.js:88:9)
    at Object.<anonymous> (/snapshot/myproject/node_modules/serialport/lib/bindings.js:3:35)
    at Module._compile (pkg/prelude/bootstrap.js:1151:22)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at Module.require (pkg/prelude/bootstrap.js:1061:31)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/snapshot/myproject/node_modules/serialport/lib/serialport.js:12:25)
```

Any ideas?

**Comment by vweevers** [comment]
See https://github.com/zeit/pkg#native-addons:

> Native addons (`.node` files) use is supported, but packaging `.node` files inside the executable is not resolved yet. You have to deploy native addons used by your project to the same directory as the executable.

**Comment by igorklopov** [comment]
@vweevers 👍  Nothing to add.

**Comment by treefort** [comment]
thanks, @vweevers! nooo idea how I missed that in the readme.

**Comment by aatronics** [comment]
Can anyone help me... I also have the same issue @treefort  while generating .exe of my node js program using pkg. node js usage serialport for some operation. but I didn't get how I can resolve this..

![img_20171009_105421](https://user-images.githubusercontent.com/25177416/31376299-1893e84e-adc2-11e7-9538-10d1a50c06fa.jpg)

**Comment by yirenkeji555** [comment]
you can copy node_modules in  xx.exe run dir
