### ISSUE TITLE
'os is not defined' error on windows

### ISSUE THREAD

**Issue by vihanb** [zeit/pkg#169]
I have a project [here](https://github.com/vsl-lang/VSL) which builds fine for mac & linux. Both executables work flawlessly but the windows versions seem to always error with:

```
$ ./vsl
pkg/prelude/bootstrap.js:1080
      throw error;
      ^

ReferenceError: os is not defined
    at getSupport (C:\snapshot\VSL\lib\cli\colorSupport.js:18:25)
    at Object.<anonymous> (C:\snapshot\VSL\lib\cli\colorSupport.js:72:13)
    at Module._compile (pkg/prelude/bootstrap.js:1151:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at Module.require (pkg/prelude/bootstrap.js:1061:31)
    at require (internal/module.js:20:19)
```

when loading `os` module. Is the `os` module not supported?

**Comment by igorklopov** [comment]
Pleas try again with `pkg@4.1.4`. Also add `libraries` directory to `package.json` `pkg.assets`
