### ISSUE TITLE
Express view engine

### ISSUE THREAD

**Issue by feed4rz** [zeit/pkg#178]
I am struggling with adding a view engine plugin called "ejs".

Here is how expressjs guide suggests adding it.
`app.set('view engine', 'ejs');`

Here is my package.json:
`{
  "name": "app",
  "version": "1.0.0",
  "description": "",
  "main": "app.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "feed4rz",
  "license": "MIT",
  "dependencies": {
    "body-parser": "^1.17.1",
    "ejs": "^2.5.6",
    "express": "^4.15.2",
    "fs": "0.0.1-security",
    "helmet": "^3.5.0",
    "mongoose": "^4.9.5",
    "node-restful": "^0.2.6",
    "request": "^2.81.0"
  },
	"pkg" : {
		"assets": [
			"views/**/*",
			"node_modules/**/*"
		]
	}
}
`

Error i get when trying to access any page:
`Error: Cannot find module 'ejs'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1217:46)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at Module.require (pkg/prelude/bootstrap.js:1101:31)
    at require (internal/module.js:20:19)
    at new View (C:\snapshot\cluster-bots\node_modules\express\lib\view.js:80:30)
    at Function.render (C:\snapshot\cluster-bots\node_modules\express\lib\application.js:570:12)
    at ServerResponse.render (C:\snapshot\cluster-bots\node_modules\express\lib\response.js:966:7)
    at router.route.get (C:\snapshot\cluster-bots\routes\panel.js:0:0)
    at Layer.handle [as handle_request] (C:\snapshot\cluster-bots\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\snapshot\cluster-bots\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\snapshot\cluster-bots\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\snapshot\cluster-bots\node_modules\express\lib\router\layer.js:95:5)
    at C:\snapshot\cluster-bots\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\snapshot\cluster-bots\node_modules\express\lib\router\index.js:335:12)`

**Comment by igorklopov** [comment]
Be sure to run `pkg package.json` (or just `pkg .`). `pkg index.js` will not work. Pkg needs `package.json` to detect dependencies, ejs among them. Because `app.set('view engine', 'ejs')` means nothing for pkg currently.

**Comment by pochuang** [comment]
pkg package.json still not working. I've got a lot of 'cannot find module xxx' error messages and can not continue compile.
