### ISSUE TITLE
Tesseract.js - Cannot find module '../common/worker.js'

### ISSUE THREAD

**Issue by johanvdb** [zeit/pkg#183]
When making use of pkg to produce a redistributable binary of a node.js project, the following error occurs when trying to use Tesseract.js

See https://gitlab.com/johantheitguy/tesseractjs-pkg for an example project (see scripts in package.json).

Error: Cannot find module '../common/worker.js'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1217:46)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at Module.require (pkg/prelude/bootstrap.js:1101:31)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/snapshot/tesseract-pkg/node_modules/tesseract.js/src/node/worker.js:1:83)
    at Module._compile (module.js:570:32)
    at Module._compile (pkg/prelude/bootstrap.js:1198:32)
    at Object.Module._extensions..js (module.js:579:10)

I have tried every permutation if script includes I can think of. I can see in their source that we include "node/worker.js" which in turn tries to require "../common/worker.js". I see the files being included when running pkg -d. 

Running the same app without pkg works as expected. The OCR result is "hello".

Thanks in advance!

**Comment by johanvdb** [comment]
Wow thanks!

**Comment by igorklopov** [comment]
Fixed in pkg@4.2.0. Please upgrade!

**Comment by johanvdb** [comment]
Tested and working perfectly 👍

**Comment by robotic1** [comment]
When making use of pkg@4.4.9 to produce a redistributable binary of a node.js project, the following error occurs when trying to use tesseract.js@2.1.4
internal/modules/cjs/loader.js:636
    throw err;
    ^
Error: Cannot find module 'C:\betting\test_pkg\--debug-port=9230'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:634:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:560:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:660:3)

Running the same app without pkg works as expected. 
Test file:
---
const {createWorker}=require('tesseract.js');
const worker = createWorker({
	logger: m => console.log(m)
});
(async () => {
	await worker.load();
	await worker.loadLanguage('eng');
	await worker.initialize('eng');
	const { data: { text } } = await worker.recognize('hello.jpg');
	console.log(text);
	await worker.terminate();
})();
---
Thanks in advance!

**Comment by sRect** [comment]
"pkg": "^4.4.9"
"tesseract.js": "^2.1.4"
```
internal/modules/cjs/loader.js:636
    throw err;
    ^

Error: Cannot find module 'E:\my\resource\recognition\dist\--debug-port=9230'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:634:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1346:46)
    at Function.Module._load (internal/modules/cjs/loader.js:560:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1375:12)
    at startup (internal/bootstrap/node.js:320:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:660:3)
```

**Comment by 3dprogramin** [comment]
"node": "v16.11.1"
"pkg": "5.8.0"
"tesseract.js": "3.0.3"

```javascript
node:internal/event_target:912
  process.nextTick(() => { throw err; });
                           ^
Error: Cannot find module '/snapshot/scraper/node_modules/tesseract.js/src/worker-script/node/index.js'
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function._resolveFilename (pkg/prelude/bootstrap.js:1955:46)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
    at MessagePort.<anonymous> (node:internal/main/worker_thread:191:24)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28)
Emitted 'error' event on Worker instance at:
    at Worker.[kOnErrorMessage] (node:internal/worker:289:10)
    at Worker.[kOnMessage] (node:internal/worker:300:37)
    at MessagePort.<anonymous> (node:internal/worker:201:57)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:643:20)
    at MessagePort.exports.emitMessage (node:internal/per_context/messageport:23:28) {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}

```
