### ISSUE TITLE
Cannot package a node app

### ISSUE THREAD

**Issue by harisvsulaiman** [zeit/pkg#187]
I cannot package a node app of just one file, using `pkg index.js -t node8-linux --verbose -d`

## Error output
```
> pkg@4.1.4
> [debug] File %1 added to queue
  /home/harisvsulaiman/work/pkg/index.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/package.json
  /home/harisvsulaiman/work/pkg/index.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/index.js
  /home/harisvsulaiman/work/pkg/index.js
> [debug] File %1 added to queue
  /home/harisvsulaiman/work/pkg
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/index.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/put/package.json
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/put/index.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/xml2js/package.json
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/xml2js/lib/xml2js.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/constants.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/index.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/message.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/index.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/handshake.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/index.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/server-handshake.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/index.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/hello-message.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/index.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/bus.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/index.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/server.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/index.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/abstract-socket/package.json
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/index.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/abstract-socket/lib/abstract_socket.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/index.js
> [debug] File %1 added to queue
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/through/package.json
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/through/index.js
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/duplexer/package.json
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/duplexer/index.js
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/from/package.json
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/from/index.js
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/map-stream/package.json
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/map-stream/index.js
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/pause-stream/package.json
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/pause-stream/index.js
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/split/package.json
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/split/index.js
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/stream-combiner/package.json
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/stream-combiner/index.js
  /home/harisvsulaiman/work/pkg/node_modules/event-stream/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/sax/package.json
  /home/harisvsulaiman/work/pkg/node_modules/xml2js/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/sax/lib/sax.js
  /home/harisvsulaiman/work/pkg/node_modules/xml2js/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/marshall.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/message.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/signature.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/message.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/dbuffer.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/message.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/unmarshall.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/message.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/header-signature.json
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/message.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/readline.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/handshake.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/stdifaces.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/bus.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/introspect.js
  /home/harisvsulaiman/work/pkg/node_modules/dbus-native/lib/bus.js
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/bindings/package.json
  /home/harisvsulaiman/work/pkg/node_modules/abstract-socket/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/bindings/bindings.js
  /home/harisvsulaiman/work/pkg/node_modules/abstract-socket/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/nan/package.json
  /home/harisvsulaiman/work/pkg/node_modules/abstract-socket/package.json
> [debug] File %1 added to queue. It was required from %2
  /home/harisvsulaiman/work/pkg/node_modules/nan/include_dirs.js
  /home/harisvsulaiman/work/pkg/node_modules/abstract-socket/package.json
> [debug] File %1 added to queue
  /home/harisvsulaiman/work
> [debug] File %1 added to queue
  /home/harisvsulaiman/work/pkg/node_modules/event-stream
> Error! TypeError: license.toLowerCase is not a function
    at isPermissive (/home/harisvsulaiman/.config/yarn/global/node_modules/pkg/lib-es5/walker.js:93:21)
    at Walker._callee2$ (/home/harisvsulaiman/.config/yarn/global/node_modules/pkg/lib-es5/walker.js:538:37)
    at tryCatch (/home/harisvsulaiman/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/harisvsulaiman/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/harisvsulaiman/.config/yarn/global/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/harisvsulaiman/.config/yarn/global/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/harisvsulaiman/.config/yarn/global/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
```
 
## index.js
```javascript
var dbus = require("dbus-native");
var sessionBus = dbus.sessionBus();
sessionBus
  .getService("org.freedesktop.Notifications")
  .getInterface(
    "/org/freedesktop/Notifications",
    "org.freedesktop.Notifications",
    function(err, notifications) {
      // dbus signals are EventEmitter events
      notifications.on("ActionInvoked", function() {
        console.log("ActionInvoked", arguments);
      });
      notifications.on("NotificationClosed", function() {
        console.log("NotificationClosed", arguments);
      });
      notifications.Notify(
        "exampl",
        0,
        "",
        "summary 3",
        "new message text",
        ["xxx yyy", "test2", "test3", "test4"],
        [],
        5,
        function(err, id) {
          //setTimeout(function() { n.CloseNotification(id, console.log); }, 4000);
        }
      );
    }
  );
```
## package.json
```json
{
  "name": "pkg",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "dependencies": {
    "dbus-native": "^0.2.2"
  }
}

```

**Comment by harisvsulaiman** [comment]
Simple debugging with a console log, gave me some insight. pkg doesn't seem to handle Dual licensed packages in dependencies.

# Debug line
```javascript
console.log(`debugging pkg name ${config.name} license ${license}`); // haris debug line
```

#  Log
```
debugging pkg name through license MIT
debugging pkg name duplexer license undefined
debugging pkg name from license MIT
debugging pkg name map-stream license undefined
debugging pkg name pause-stream license MIT,Apache2
> Error! TypeError: license.toLowerCase is not a function
    at isPermissive (/home/harisvsulaiman/work/pkg/node_modules/pkg/lib-es5/walker.js:98:21)
    at Walker._callee2$ (/home/harisvsulaiman/work/pkg/node_modules/pkg/lib-es5/walker.js:746:43)
    at tryCatch (/home/harisvsulaiman/work/pkg/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/home/harisvsulaiman/work/pkg/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/home/harisvsulaiman/work/pkg/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/home/harisvsulaiman/work/pkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /home/harisvsulaiman/work/pkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at <anonymous>
error Command failed with exit code 2.
```
Replacing the package.json file with one license (just to test) works.

**Comment by igorklopov** [comment]
Fixed in https://github.com/zeit/pkg/commit/48150ab964cbd639486b0bb37dd902692bed4ba5 Thanks! Please wait for 4.2.2

**Comment by harisvsulaiman** [comment]
@igorklopov Should have been fixed here https://github.com/dominictarr/pause-stream/issues/6.
