### ISSUE TITLE
[Bug]: Invalid exe

### ISSUE THREAD

**Issue by nenadalm** [zeit/pkg#197]
Hi. I tried to create exe with this app but without success. I've created repo with minimal code I could reproduce the issue with: https://github.com/nenadalm/nodeexe

Output of the commands is here: https://github.com/nenadalm/nodeexe/blob/master/output.txt

Wrong there is the following error, which should not happen:
```
TypeError: winston.transports.Console is not a constructor
    at new exports.Container (C:\snapshot\nodeexe\node_modules\winston-uber\lib\winston\container.js:23:7)
    at Object.<anonymous> (C:\snapshot\nodeexe\node_modules\winston-uber\lib\winston.js:51:19)
    at Module._compile (pkg/prelude/bootstrap.js:1225:22)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at Module.require (pkg/prelude/bootstrap.js:1135:31)
    at require (internal/module.js:20:19)
```

The app contains 2 scripts
- `start` - runs program by invoking `node src/index.js` - this works
- `build` - creates rc.exe, which throws unexpected error when executed

Expected result is this error: https://github.com/nenadalm/nodeexe/blob/master/src/index.js#L32 shown in console.

I was playing with it on 64 bit version of Windows 10.

**Comment by igorklopov** [comment]
Please upgrade to pkg@4.2.4

**Comment by nenadalm** [comment]
thanks. new version works.
