### ISSUE TITLE
pg-escape: Directory/file was not included into executable at compilation stage

### ISSUE THREAD

**Issue by ashking** [zeit/pkg#216]
HI there,

am using pg-escape npm package with my express app and when I package it with pkg and run the app I end up with the following error:

```
pkg/prelude/bootstrap.js:1080
      throw error;
      ^

Error: File '/**/express-pkg/node_modules/pg-escape/reserved.txt' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (pkg/prelude/bootstrap.js:373:17)
    at readFileFromSnapshot (pkg/prelude/bootstrap.js:592:29)
    at Object.fs.readFileSync (pkg/prelude/bootstrap.js:635:18)
    at Object.<anonymous> (/snapshot/express-pkg/node_modules/pg-escape/index.js:13:14)
    at Module._compile (pkg/prelude/bootstrap.js:1151:22)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
```

Here's my package.json:
```
"pkg": {
    "assets": "./**/express-pkg/node_modules/pg-escape/reserved.txt"
  },
  "bin": {
    "app": "app.js"
  }
```

Am using the latest pkg@4.2.4. 

@igorklopov Am I missing something here? 
Please help

**Comment by ashking** [comment]
Please ignore. I got it working. My entry in package.json was wrong:

I rectified it by 

```
"pkg": {
    "assets": "node_modules/pg-escape/**/*.*"
  },
  "bin": "app.js"
```
