### ISSUE TITLE
"TypeError: this is not a typed array" Error on compilation

### ISSUE THREAD

**Issue by Kradre** [zeit/pkg#234]
# index.js
`setInterval(function () {
	console.log("Empty test")
},3000);`
# Output in pkg
`> pkg@4.2.4
> Targets not specified. Assuming:
  node4-linux-x64, node4-macos-x64, node4-win-x64
> Error! TypeError: this is not a typed array.
    at Function.from (native)
    at exports.default (/usr/local/lib/node_modules/pkg/lib-es5/packer.js:59:67)
    at _callee3$ (/usr/local/lib/node_modules/pkg/lib-es5/index.js:765:45)
    at tryCatch (/usr/local/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:65:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (/usr/local/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:303:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (/usr/local/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/usr/local/lib/node_modules/pkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:17:30)
    at /usr/local/lib/node_modules/pkg/node_modules/babel-runtime/helpers/asyncToGenerator.js:28:13
    at run (/usr/local/lib/node_modules/pkg/node_modules/core-js/library/modules/es6.promise.js:66:22)
    at /usr/local/lib/node_modules/pkg/node_modules/core-js/library/modules/es6.promise.js:79:30
`

I've just installed pkg and it dosen't seems to work.

**Comment by igorklopov** [comment]
You have too old version of `pkg`. Please update to at least `4.8.4`
