### ISSUE TITLE
Compilation of µWebSockets has failed

### ISSUE THREAD

**Issue by fraxken** [zeit/pkg#238]
Hi,

When i try to execute my .exe for windows it say : 

```
pkg/prelude/bootstrap.js:1155
      throw error;
      ^

Error: Compilation of µWebSockets has failed and there is no pre-compiled binary available for your system. Please install a supported C++11 compiler and reinstall the module 'uws'.
    at native (G:\snapshot\Agent\node_modules\uws\uws.js:38:19)
    at Object.<anonymous> (G:\snapshot\Agent\node_modules\uws\uws.js:42:3)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at Module.require (pkg/prelude/bootstrap.js:1136:31)
    at require (internal/module.js:11:18)
```

When my code is not compiled with pkg i have no problem with the compilation of uWS (and i have installed a compiler installed too).

Any idea ? Maybe i'm doing something bad somewhere ?

Thanks for your time.

Best Regards,
Thomas

**Comment by igorklopov** [comment]
Please deploy `uws_*.node` files next to executable. https://github.com/zeit/pkg#native-addons
