### ISSUE TITLE
Hangs when running via API

### ISSUE THREAD

**Issue by hughdunne** [zeit/pkg#254]
I tried to run pkg as part of a node script, following the example in the README:

    const { exec } = require('pkg');
    exec(args).then(() => console.log("Finished generating exe"));

But the promise is never resolved or rejected even after the output file is created.

My node version is v8.6.0

Running on Windows 10

**Comment by igorklopov** [comment]
Failed to reproduce. It always outputs `Finished generating exe` for me. Please provide `args`.

**Comment by hughdunne** [comment]
Not sure what I did wrong but it's working for me now. Withdrawing this issue.

**Comment by hughdunne** [comment]
I remember the issue now - it works ok when generating one binary, but I get an error when trying to generate more than one.

    async function fred() {
        console.log('before win');
        try {
            await exec (['packages/prog_exercise_search/bin/www', '--target', 'win', '--output', 'fred.exe']);
        } catch (err) {
            console.log(err);
        }
        console.log('after win');
        console.log('before linux');
        try {
            await exec (['packages/prog_exercise_search/bin/www', '--target', 'linux', '--output', 'fred.linux']);
        } catch (err) {
            console.log(err);
        }
        console.log('after linux');
        console.log('before macos');
        try {
            await exec (['packages/prog_exercise_search/bin/www', '--target', 'macos', '--output', 'fred.macos']);
        } catch (err) {
            console.log(err);
        }
        console.log('after macos');
        process.exit(0);
    }

I get the following output:

    before win
    > pkg@4.2.5
    after win
    before linux
    > pkg@4.2.5
    events.js:182
          throw er; // Unhandled 'error' event
          ^

    Error: This socket has been ended by the other party
        at Socket.writeAfterFIN [as write] (net.js:354:12)
        at fabricate (C:\Users\tclgu\git_repos\tufan-cli-pkgr\node_modules\pkg\lib-es5\fabricator.js:88:15)
        at fabricateTwice (C:\Users\tclgu\git_repos\tufan-cli-pkgr\node_modules\pkg\lib-es5\fabricator.js:96:3)
        at MultiStream._queue (C:\Users\tclgu\git_repos\tufan-cli-pkgr\node_modules\pkg\lib-es5\producer.js:116:53)
        at MultiStream._next (C:\Users\tclgu\git_repos\tufan-cli-pkgr\node_modules\multistream\index.js:72:10)
        at Meter.onEnd (C:\Users\tclgu\git_repos\tufan-cli-pkgr\node_modules\multistream\index.js:119:10)
        at Object.onceWrapper (events.js:314:30)
        at emitNone (events.js:110:20)
        at Meter.emit (events.js:207:7)
        at endReadableNT (_stream_readable.js:1059:12)

Afterwards, `fred.win` and `fred.linux` exist but not `fred.macos`.
