### ISSUE TITLE
Error: There are no suitable editions for this environment

### ISSUE THREAD

**Issue by jokyme** [zeit/pkg#256]
what's the problem?

```
Error: There are no suitable editions for this environment:
opts: { cwd: 'C:\\snapshot\\crawler-node\\node_modules\\extract-opts',
  package: 'extract-opts' }
editions: [ { description: 'Source + ESNext + Require',
    entry: 'source/index.js',
    directory: 'source',
    syntaxes:
     [ 'javascript',
       'esnext',
       'require',
       'const',
       'destructuring',
       'defaults' ] },
  { description: 'Babel Compiled + ES2015 + Require',
    entry: 'es2015/index.js',
    directory: 'es2015',
    syntaxes: [ 'javascript', 'es2015', 'require' ] } ]
failures: [ Error: Failed to load the edition due to a load error:
edition: { description: 'Source + ESNext + Require',
  entry: 'source/index.js',
  directory: 'source',
  syntaxes:
   [ 'javascript',
     'esnext',
     'require',
     'const',
     'destructuring',
     'defaults' ] }
error: 'Error: Cannot find module \'C:\\snapshot\\crawler-node\\node_modules\\extract-opts\\source\\index.js\'\n    at Function.Module._resolveFilename (module.js:527:15)\n    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1252:46)\n    at Function.Module._load (module.js:476:23)\n    at Module.require (module.js:568:17)\n    at Module.require (pkg/prelude/bootstrap.js:1136:31)\n    at Object.require (internal/module.js:11:18)\n    at requireEdition (C:\\snapshot\\crawler-node\\node_modules\\extract-opts\\node_modules\\editions\\es2015\\index.js:138:15)\n    at requireEditions (C:\\snapshot\\crawler-node\\node_modules\\extract-opts\\node_modules\\editions\\es2015\\index.js:179:11)\n    at Object.requirePackage (C:\\snapshot\\crawler-node\\node_modules\\extract-opts\\node_modules\\editions\\es2015\\index.js:207:9)\n    at Object.<anonymous> (C:\\snapshot\\crawler-node\\node_modules\\extract-opts\\index.js:3:38)'
    at new DetailedError (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:28:109)
    at requireEdition (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:141:26)
    at requireEditions (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:179:11)
    at Object.requirePackage (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:207:9)
    at Object.<anonymous> (C:\snapshot\crawler-node\node_modules\extract-opts\index.js:3:38)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3),
  Error: Failed to load the edition due to a load error:
edition: { description: 'Babel Compiled + ES2015 + Require',
  entry: 'es2015/index.js',
  directory: 'es2015',
  syntaxes: [ 'javascript', 'es2015', 'require' ] }
error: 'Error: Cannot find module \'C:\\snapshot\\crawler-node\\node_modules\\extract-opts\\es2015\\index.js\'\n    at Function.Module._resolveFilename (module.js:527:15)\n    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1252:46)\n    at Function.Module._load (module.js:476:23)\n    at Module.require (module.js:568:17)\n    at Module.require (pkg/prelude/bootstrap.js:1136:31)\n    at Object.require (internal/module.js:11:18)\n    at requireEdition (C:\\snapshot\\crawler-node\\node_modules\\extract-opts\\node_modules\\editions\\es2015\\index.js:138:15)\n    at requireEditions (C:\\snapshot\\crawler-node\\node_modules\\extract-opts\\node_modules\\editions\\es2015\\index.js:179:11)\n    at Object.requirePackage (C:\\snapshot\\crawler-node\\node_modules\\extract-opts\\node_modules\\editions\\es2015\\index.js:207:9)\n    at Object.<anonymous> (C:\\snapshot\\crawler-node\\node_modules\\extract-opts\\index.js:3:38)'
    at new DetailedError (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:28:109)
    at requireEdition (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:141:26)
    at requireEditions (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:179:11)
    at Object.requirePackage (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:207:9)
    at Object.<anonymous> (C:\snapshot\crawler-node\node_modules\extract-opts\index.js:3:38)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3) ]
    at new DetailedError (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:28:109)
    at requireEditions (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:186:8)
    at Object.requirePackage (C:\snapshot\crawler-node\node_modules\extract-opts\node_modules\editions\es2015\index.js:207:9)
    at Object.<anonymous> (C:\snapshot\crawler-node\node_modules\extract-opts\index.js:3:38)
    at Module._compile (pkg/prelude/bootstrap.js:1226:22)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
```

**Comment by Jimut** [comment]
I am also facing this problem. Can you elaborate how you solved this? @jokyme

**Comment by felipebutcher** [comment]
Me too. Having this on windows while the same project works on mac and linux.

**Comment by venkatarun** [comment]
Me too. facing same issue. previously, it was working. I'm using node8 and linux to create packages

**Comment by essivision** [comment]
Me too

**Comment by wzhongbi** [comment]
Me too
