### ISSUE TITLE
Unable to write to a packaged JSON file

### ISSUE THREAD

**Issue by preraksola** [zeit/pkg#381]
I have a JSON file packaged in the executable. While I am able to read the JSON file, I am unable to write to it. The executable terminates with an exception on write command.

The code that I use for writing is:  
```
const jsonFile    = require ( 'jsonfile' );
let installJson   = path.join ( __dirname, 'env/config-install.json' );
let installConfig = jsonFile.readFileSync ( installJson );

//This prints the correct content
console.log ( installConfig );
 
//Exception at this line
jsonFile.writeFileSync ( installJson, installConfig );
```

The exception stacktrace is:

```
Preraks-Mac-mini:www prerak$ ./executable-macos 
{ port: 3000, env: 'development' }
pkg/prelude/bootstrap.js:262
  if (error) throw error;
             ^

Error: Cannot write to packaged file
    at writeToSnapshot (pkg/prelude/bootstrap.js:567:16)
    at Object.fs.writeSync (pkg/prelude/bootstrap.js:575:12)
    at Object.fs.writeFileSync (fs.js:1324:24)
    at Object.writeFileSync (/snapshot/www/node_modules/jsonfile/index.js:116:13)
    at module.exports (/snapshot/www/config/init.js:48:11)
    at Object.<anonymous> (/snapshot/www/server.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
    at Object.Module._extensions..js (module.js:650:10)
    at Module.load (module.js:558:32)
    at tryModuleLoad (module.js:501:12)
```

I also added the JSON file in `assets` and/or `scripts` in `package.json` but the result was the same exception.

**Comment by jschlanger12** [comment]
Any update on this? Seems I'm running into the same issue and cannot figure it out.

**Comment by igorklopov** [comment]
Currently the internal file system is read-only, mostly because it is not persistent. Unlike real file system, changes you make to snapshot do not survive application restart. Please consider storing changes to real file system. I advice you checking if config file exists on real file system. If not read default file from snapshot.

**Comment by hipstersmoothie** [comment]
pkg snapshot file system is read only. closing issue

**Comment by tiulinh** [comment]
can write: var filePath = process.cwd()+'/your_file_here.ext';
