### ISSUE TITLE
Cannot find module './charset.js'

### ISSUE THREAD

**Issue by jschlanger12** [zeit/pkg#387]
I am trying to package an express and express-admin server and am having issues when running the .exe
```
pkg/prelude/bootstrap.js:1172
      throw error;
      ^

Error: Cannot find module './charset.js'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:534:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1269:46)
    at Function.Module._load (module.js:464:25)
    at Module.require (module.js:577:17)
    at Module.require (pkg/prelude/bootstrap.js:1153:31)
    at require (internal/module.js:11:18)
    at C:\snapshot\Monolith_backend\node_modules\express-admin\node_modules\negotiator\lib\negotiator.js:21:16
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\snapshot\Monolith_backend\node_modules\express-admin\node_modules\negotiator\lib\negotiator.js:19:18)
    at Module._compile (pkg/prelude/bootstrap.js:1243:22)
```

This is what i get when I try to execute it. Any Ideas?

**Comment by rameshnkl** [comment]
Is it fixed? I am also getting the same error.

**Comment by rameshnkl** [comment]
@jschlanger12 , I am also getting the same error, could you please explain what needs to be done? Thanks.
