### ISSUE TITLE
Error when using wmi-client

### ISSUE THREAD

**Issue by s-h-a-d-o-w** [zeit/pkg#399]
After packaging this little tool I'm working on: https://github.com/s-h-a-d-o-w/spotify-ad-blocker

I got this error upon execution:
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn wmic ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3
```

OS: Win7 x64
Node version: 8.11.1

**Comment by HardlyMirage** [comment]
You're using the WMI Client, which should be located at `C:\WINDOWS\System32\wbem`. Add that folder to your `PATH` and it should work.

**Comment by s-h-a-d-o-w** [comment]
Nope, still the same error, unfortunately.

**Comment by s-h-a-d-o-w** [comment]
I just realized that apparently, once packaged, no globally available executables are found. Consider this simple example:

```javascript
var spawn = require('child_process').spawn;

var child = spawn("python", ['-m', 'SimpleHTTPServer'], {
    cwd: __dirname,
    stdio: ['inherit', 'inherit', 'inherit']
});
```

Works fine when executed with node directly but once packaged and executing the .exe, the result is:
```
Error: spawn python ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1299:13)
    at startup (bootstrap_node.js:223:16)
    at bootstrap_node.js:644:3
```
