### ISSUE TITLE
Mention 'cross-cpu-compilation' limitation in docs

### ISSUE THREAD

**Issue by msolters** [zeit/pkg#40]
Hi, I am cross-compiling for `arm6` or `arm7` on 64-bit Ubuntu host.

Regardless of if I use `armv6` or `armv7`, and regardless of if I use `node6` or `node7`, I always get the following error:

```
/home/msolters/.pkg-cache/v1.9/fetched-v6.10.0-linux-armv7: 1: /home/msolters/.pkg-cache/v1.9/fetched-v6.10.0-linux-armv7: Syntax error: word unexpected (expecting ")")
> Error! Error: Not able to compile for 'armv7' here
    at Socket.<anonymous> (/home/msolters/.nvm/versions/node/v6.10.0/lib/node_modules/pkg/lib-es5/producer.js:43:25)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at onwriteError (_stream_writable.js:346:10)
    at onwrite (_stream_writable.js:364:5)
    at WritableState.onwrite (_stream_writable.js:90:5)
    at fireErrorCallbacks (net.js:468:13)
    at Socket._destroy (net.js:509:3)
    at WriteWrap.afterWrite (net.js:803:10)
```

**Comment by igorklopov** [comment]
`pkg` can currently crosscompile to same cpu that host machine has. Probably need to specify it explicitly in docs.

**Comment by igorklopov** [comment]
There is a solution to make binaries for ARM from Ubuntu x64: https://github.com/zeit/pkg/issues/145#issuecomment-311150484
