### ISSUE TITLE
node10: process.binding(...).internalModuleReadFile is not a function

### ISSUE THREAD

**Issue by SMotaal** [zeit/pkg#467]
Just a head up that in newer node versions `process.binding(...).internalModuleReadFile` is removed in favour of a JSON-specific variant - not sure what it will end up being.

Although in some versions this seems to be a simple rename, it is only reasonable to assume change implementation will follow, and my best guess is that it eventually will be the goto method that allows fast sync read of "package.json".

```js
  require('./test')  // test has index.js and no package.json
```

```apl
pkg/prelude/bootstrap.js:1176
      throw error;
      ^

TypeError: process.binding(...).internalModuleReadFile is not a function
    at Object.fs.internalModuleReadFile.fs.internalModuleReadJSON (pkg/prelude/bootstrap.js:1127:36)
    at internalModuleReadJSON (internal/modules/cjs/loader.js:31:68)
    at readPackage (internal/modules/cjs/loader.js:156:16)
    at tryPackage (internal/modules/cjs/loader.js:172:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:282:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:589:25)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1270:44)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
```

**Comment by theogravity** [comment]
Encountered this issue too. Might have been premature for me to use node 10 for now.

Also noticed that pkg only does `10.4.1` instead of the latest `10.7.0`.

**Comment by bergheim** [comment]
This fixes the issue for me (no problems since I added the pull request): #461

**Comment by makepanic** [comment]
Any chance on getting any of the open PRs for this issue merged?

We're also seeing this issue on node `10.9.0`.

**Comment by mvila** [comment]
Any progress about this issue? I'd love to be able to upgrade my packaged tools to Node v10.

**Comment by simonkberg** [comment]
Head up: Node 10 is scheduled to be promoted to LTS at the [end of this month](https://github.com/nodejs/Release/blob/master/schedule.json#L48). Is this project still being maintained?
