### ISSUE TITLE
Error: EPERM: operation not permitted, scandir '/.Spotlight-V100'

### ISSUE THREAD

**Issue by jsappme** [zeit/pkg#482]
I was able to pkg a few times before getting the following issue: 

```
$ pkg index.js
> pkg@4.3.3
> Targets not specified. Assuming:
  node8-linux-x64, node8-macos-x64, node8-win-x64
> Error! Error: EPERM: operation not permitted, scandir '/.Spotlight-V100'
    at Object.fs.readdirSync (fs.js:911:18)
    at exports.readdir (/usr/local/lib/node_modules/pkg/node_modules/@mrmlnc/readdir-enhanced/lib/sync/fs.js:18:20)
    at Object.safeCall [as safe] (/usr/local/lib/node_modules/pkg/node_modules/@mrmlnc/readdir-enhanced/lib/call.js:24:8)
    at DirectoryReader.readNextDirectory (/usr/local/lib/node_modules/pkg/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:78:10)
    at Readable.DirectoryReader.stream._read (/usr/local/lib/node_modules/pkg/node_modules/@mrmlnc/readdir-enhanced/lib/directory-reader.js:57:18)
    at Readable.read (_stream_readable.js:445:10)
    at readdirSync (/usr/local/lib/node_modules/pkg/node_modules/@mrmlnc/readdir-enhanced/lib/sync/index.js:27:21)
    at Function.readdirSyncStat (/usr/local/lib/node_modules/pkg/node_modules/@mrmlnc/readdir-enhanced/lib/index.js:34:10)
    at ReaderSync.dynamicApi (/usr/local/lib/node_modules/pkg/node_modules/fast-glob/out/providers/reader-sync.js:61:24)
    at ReaderSync.api (/usr/local/lib/node_modules/pkg/node_modules/fast-glob/out/providers/reader-sync.js:53:25)
```

so I try to run it on my Windows 10 machine, it worked one time and now when I try to run the same command it also gives me an error:

```
>pkg index.js
> pkg@4.3.3
> Targets not specified. Assuming:
  node8-linux-x64, node8-macos-x64, node8-win-x64
> Error! Error: EBUSY: resource busy or locked, lstat 'C:\hiberfil.sys'
    at Object.fs.lstatSync (fs.js:941:11)
    at exports.lstat (C:\Users\herve\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\sync\fs.js:58:20)
    at Object.safeCall [as safe] (C:\Users\herve\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\call.js:24:8)
    at stat (C:\Users\herve\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\stat.js:19:8)
    at DirectoryReader.processItem (C:\Users\herve\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\directory-reader.js:178:5)
    at array.forEach.item (C:\Users\herve\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\sync\for-each.js:14:5)
    at Array.forEach (<anonymous>)
    at Object.syncForEach [as forEach] (C:\Users\herve\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\sync\for-each.js:13:9)
    at call.safe (C:\Users\herve\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\directory-reader.js:87:16)
    at onceWrapper (C:\Users\herve\AppData\Roaming\npm\node_modules\pkg\node_modules\@mrmlnc\readdir-enhanced\lib\call.js:45:17)
```

**Comment by jsappme** [comment]
the issue comes from the firebase nm pkg
