### ISSUE TITLE
Using NPM internally fails to find module `node-gyp`

### ISSUE THREAD

**Issue by ramtinsoltani** [zeit/pkg#522]
I'm using NPM programmatically to provide an API for installing user-provided NPM modules. While using `npm.commands.install` the following error is thrown:

```
{ Error: Cannot find module 'node-gyp/bin/node-gyp'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (module.js:545:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at resolveFileName (/snapshot/chisel/node_modules/npm/node_modules/npm-lifecycle/node_modules/resolve-from/index.js:29:39)
    at resolveFrom (/snapshot/chisel/node_modules/npm/node_modules/npm-lifecycle/node_modules/resolve-from/index.js:43:9)
    at module.exports (/snapshot/chisel/node_modules/npm/node_modules/npm-lifecycle/node_modules/resolve-from/index.js:46:41)
    at Object.<anonymous> (/snapshot/chisel/node_modules/npm/node_modules/npm-lifecycle/index.js:18:31)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/chisel/node_modules/npm/lib/utils/lifecycle.js:4:19)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22) code: 'MODULE_NOT_FOUND', pkg: true }
```

Why is the NPM package failing to find `node-gyp/bin/node-gyp`? Is there anyway to include this inside the binary?

I've tried adding `node_modules/node-gyp/bin/node-gyp.js` to assets and also have declared it as a project dependency inside `package.json`.

**Comment by abehaskins** [comment]
I'm also seeing this, I tried pulling in `npm` in a couple ways, but wasn't able to get around this. Very curious to hear if this is some core issue with using `node-gyp` packages or something that can be worked around.

**Comment by abehaskins** [comment]
Turns out this is just an issue of a missing asset which doesn't get bundled. You can add this to your `package.json` to ensure that the needed files get bundled...

```
  "pkg": {
    "scripts": [
      "node_modules/npm/src/**/*.js"
    ],
    "assets": [
      "node_modules/npm/bin/**/*",
      "node_modules/npm/node_modules/node-gyp/**/*"
    ]
  }
```

This probably is overly aggressive and will result in a large bundle, but it works!
