### ISSUE TITLE
pkg with vuetify's webpack-ssr

### ISSUE THREAD

**Issue by rucciva** [zeit/pkg#527]
Hi, i've been trying to use pkg 4.3.4 on my project that is based on  [vuetify's webpack-ssr template](https://github.com/vuetifyjs/webpack-ssr/tree/master/template). The compilation is success but when i'm trying to run it, i always get this error

```javascript
Error: Cannot find module 'babel-runtime/core-js/promise' from '/snapshot/app/public'
    at Function.module.exports [as sync] (/snapshot/app/node_modules/resolve/lib/sync.js:43:15)
    at r (/snapshot/app/node_modules/vue-server-renderer/build.js:8343:44)
    at Object.<anonymous> (server-bundle.js:1:1867)
    at t (server-bundle.js:1:177)
    at Object.<anonymous> (server-bundle.js:1:3666)
    at t (server-bundle.js:1:177)
    at module.exports.n.exports.n (server-bundle.js:1:811)
    at Object.<anonymous> (server-bundle.js:1:821)
    at evaluateModule (/snapshot/app/node_modules/vue-server-renderer/build.js:8349:21)
    at SourceMapConsumer (/snapshot/app/node_modules/vue-server-renderer/build.js:8407:18)
    at new Promise (<anonymous>)
    at /snapshot/app/node_modules/vue-server-renderer/build.js:8399:14
    at Object.renderToString (/snapshot/app/node_modules/vue-server-renderer/build.js:8575:9)
    at render (/snapshot/app/server.js:0:0)
    at Layer.handle [as handle_request] (/snapshot/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/snapshot/app/node_modules/express/lib/router/route.js:137:13)
```

here is my addtion to the `package.json`

```json
...
"bin": {
    "app": "./server.js"
  },
"pkg": {
    "assets": [
      "static/**/*",
      "public/**/*",
      "assets/index.template.html"
    ]
  }
...
```

and here os the comman to run pkg

```bash
npm install &&\
npm run build &&\
NODE_ENV=production pkg . -t ${PKG_NODE_ARCH} --output /usr/local/bin/app
```

when running with debug, i can verify that the transpiled scripts (`/public/**.js`) are included in the package

```
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/0.f933c05bd20f87f414f8.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/1.f3acb84c28a3720b85bd.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/2.4591f2752b5c48b731c3.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/3.dbc6079b3e01dcb3e4f4.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/4.5d99aa89a2e2c9eb3523.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/5.124f871daa7951dd73b3.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/6.cc826496bea8b8c3a284.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/7.3795b046f7cc4229d3b7.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/8.a080ef2e16ea663410b8.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/app.0e70574caf0d57fc0ee3.js
> [debug] The file was included as asset content
  /src/app/public/common.0e70574caf0d57fc0ee3.css
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/manifest.76017d0db517b65eb985.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/vendor.e9e879ce45808bbe2000.js
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/vue-ssr-client-manifest.json
> [debug] The file was included as DISCLOSED code (with sources)
  /src/app/public/vue-ssr-server-bundle.json
> [debug] The file was included as asset content
  /src/app/assets/index.template.html
``` 

any idea on how to resolve this problem?

*btw, the project run fine if directly using node (`npm run start`)

**Comment by rucciva** [comment]
turns out that the template exclude script in `node_modules` on transpile phase. I just need to comment out [this line](https://github.com/vuetifyjs/webpack-ssr/blob/master/template/build/webpack.server.config.js#L17-L23) so that the script in public contains all the dependency, *and probably need to update the webpack as the build fail when uglify-ing.
overall, pkg is still working great :cheers:
