### ISSUE TITLE
Error when using googleapis

### ISSUE THREAD

**Issue by conoro** [zeit/pkg#53]
My app uses the Google Sheets API. 

pkg generates the binaries ok but throws the following error when I run that binary:

```

/snapshot/Users/conoroneill/gitwork/yunmai-data-extract/node_modules/googleapis/lib/googleapis.js:62
fs.readdirSync(path.join(__dirname, '../apis')).forEach(function (file) {
   ^

Error: Directory '/Users/conoroneill/gitwork/yunmai-data-extract/node_modules/googleapis/apis' was not included into executable at compilation stage. Please recompile adding it as asset or script.
    at error_ENOENT (evalmachine.<anonymous>:0)
    at readdirFromSnapshot (evalmachine.<anonymous>:0)
    at Object.fs.readdirSync (evalmachine.<anonymous>:0)
    at Object.<anonymous> (/snapshot/Users/conoroneill/gitwork/yunmai-data-extract/node_modules/googleapis/lib/googleapis.js:62:4)
    at Module._compile (module.js:570:32)
    at Module._compile (evalmachine.<anonymous>:0)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)

```
I've tried many variations on 

```
 "pkg": {
    "assets": "node_modules/googleapis/apis/**/*"
  }
```

But when I use --debug, I don't see the files being added. Am I missing something obvious in the path or glob?

**Comment by igorklopov** [comment]
Unfortunately currently collector takes additional information from `package.json` of package or from `dictionary`, not from your project's `package.json`. Feel free to post new issues here! Thanks!

**Comment by igorklopov** [comment]
Fiexd by https://github.com/zeit/pkg/commit/99ac8c1b515929346612dc3d457ff895c8aeaa39

**Comment by conoro** [comment]
Thanks! Working perfectly now.
