### ISSUE TITLE
Applying patches Error: spawn patch ENOENT

### ISSUE THREAD

**Issue by klymsoftware** [zeit/pkg#534]
I'm trying to compile the npm package http-server into an executable to be run on a machine without node.js or npm installed.

here is the package:
https://www.npmjs.com/package/http-server

I call: 
D:\test>pkg http-server -b -t node8-win-x64

here's the output:
> pkg@4.3.4
> Building base binary from source:
  built-v8.11.3-win-x64
> Cloning Node.js repository from GitHub...
  git                          [====================] 100%
> Checking out v8.11.3
> Applying patches

> Error! Error: spawn patch ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

any help is appreciated.

**Comment by SmirnovM91** [comment]
+1

**Comment by yuzd** [comment]
+1
