### ISSUE TITLE
pkg on sailsjs executes to infinite loops

### ISSUE THREAD

**Issue by navalpatel5** [zeit/pkg#535]
I have tried something quite simple to being with, just created fresh sailsjs(v1.0) project, npm install, got 'sails lift' working on port 1337 and then finally built the exe using zeit/pkg. Upon running the exe, i get this error which is absolutely non-debugable from sails perspective

"pkg": {
    "scripts": ["api/**/*.js", "config/**/*.js", "scripts/**/*.js", "tasks/**/*.js"],
    "assets": ["views/**/*", "assets/**/*"]
  }

F:\sails-test>sails-test.exe
pkg/prelude/bootstrap.js:1176
throw error;
^

RangeError: Maximum call stack size exceeded
at Object.basename (path.js:817:30)
at projectToNearby (pkg/prelude/bootstrap.js:209:21)
at findNativeAddonSyncFreeFromRequire (pkg/prelude/bootstrap.js:219:19)
at findNativeAddonForExists (pkg/prelude/bootstrap.js:999:21)
at existsFromSnapshot (pkg/prelude/bootstrap.js:1008:25)
at Object.fs.existsSync (pkg/prelude/bootstrap.js:1020:12)
at findNativeAddonSyncFreeFromRequire (pkg/prelude/bootstrap.js:220:21)
at findNativeAddonForExists (pkg/prelude/bootstrap.js:999:21)
at existsFromSnapshot (pkg/prelude/bootstrap.js:1008:25)
at Object.fs.existsSync (pkg/prelude/bootstrap.js:1020:12)
at findNativeAddonSyncFreeFromRequire (pkg/prelude/bootstrap.js:220:21)
at findNativeAddonForExists (pkg/prelude/bootstrap.js:999:21)
at existsFromSnapshot (pkg/prelude/bootstrap.js:1008:25)
at Object.fs.existsSync (pkg/prelude/bootstrap.js:1020:12)
at findNativeAddonSyncFreeFromRequire (pkg/prelude/bootstrap.js:220:21)
at findNativeAddonForExists (pkg/prelude/bootstrap.js:999:21)

**Comment by navalpatel5** [comment]
Hello People,

I have tried debugging the software too and have come to a point beyond which only your expertise can expedite the process.

in the file 'machinepack-redis/index.js'

we have the following code:

module.exports = require('machine').pack({
  pkg: require('./package.json'),
  dir: __dirname
});

When i make the exe using zeit's pkg, this section particularly leads to the crash that I have mentioned above. Looks like the code within is trying to write into the snapshot drive which is not possible (as per the documentation by zeit). any pointers !
