### ISSUE TITLE
SyntaxError: Invalid or unexpected token (function (exports, require, module, __filename, __dirname) { ����

### ISSUE THREAD

**Issue by chiragpurohit71085** [zeit/pkg#576]
I tried to create package from example. Packaging was done without error but when I tried to run with node express-example it gave me following error

/Node-Socket/pkg/examples/express/express-example:1
(function (exports, require, module, __filename, __dirname) { ����
                                                              ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3

I have also tried with very simple app which does not require any node_modules etc but same error 

For example I tried with 

var http = require('http');

http.createServer(function (req, res) {
    res.writeHead(200, {'Content-Type': 'text/html'});
    res.end('Hello World!');

}).listen(8080);

when I created package and tried to run I got the same error.

**Comment by chiragpurohit71085** [comment]
There was issue with my installation.
