### ISSUE TITLE
There is an issue with node-fibers

### ISSUE THREAD

**Issue by chiragpurohit71085** [zeit/pkg#577]
`/snapshot/sample_node_socket_express/node_modules/synchronize/node_modules/fibers/bin/darwin-x64-57/fibers.node` is missing.

Try running this to fix the issue: /sample_node_socket_express/nodetest-macos /snapshot/sample_node_socket_express/node_modules/synchronize/node_modules/fibers/build
pkg/prelude/bootstrap.js:1176
      throw error;
      ^

Error: Missing binary. See message above.
    at Object.<anonymous> (/snapshot/sample_node_socket_express/node_modules/synchronize/node_modules/fibers/fibers.js:20:8)
    at Module._compile (pkg/prelude/bootstrap.js:1252:22)
    at Object.Module._extensions..js (module.js:661:10)
    at Module.load (module.js:563:32)
    at tryModuleLoad (module.js:503:12)
    at Function.Module._load (module.js:495:3)
    at Module.require (module.js:594:17)
    at Module.require (pkg/prelude/bootstrap.js:1157:31)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/snapshot/sample_node_socket_express/node_modules/synchronize/sync.js:3:13)

**Comment by chiragpurohit71085** [comment]
This issue is not related with pkg. If any body is facing this issue please refer

https://github.com/laverdet/node-fibers/issues/353

Note :  As I was facing issue in synchronize package, I have made changes in 

/sample_node_socket_express/node_modules/synchronize/node_modules/fibers/fibers.js
