### ISSUE TITLE
Cannot package a node app

### ISSUE THREAD

**Issue by sakthivel4809** [zeit/pkg#608]
I am getting this error when I am running pkg index.js 
TypeError: Expected `cwd` to be of type `string` but received type `undefined`
    at module.exports.sync (C:\Users\sakthivelbn\AppData\Roaming\npm\node_modules\pkg\node_modules\dir-glob\index.js:56:9)
    at globDirs (C:\Users\sakthivelbn\AppData\Roaming\npm\node_modules\pkg\node_modules\globby\index.js:58:9)
    at getPattern (C:\Users\sakthivelbn\AppData\Roaming\npm\node_modules\pkg\node_modules\globby\index.js:61:64)
    at globTasks.reduce (C:\Users\sakthivelbn\AppData\Roaming\npm\node_modules\pkg\node_modules\globby\index.js:107:19)
    at Array.reduce (<anonymous>)
    at Function.module.exports.sync (C:\Users\sakthivelbn\AppData\Roaming\npm\node_modules\pkg\node_modules\globby\index.js:106:26)
    at collect (C:\Users\sakthivelbn\AppData\Roaming\npm\node_modules\pkg\lib-es5\walker.js:145:27)
    at expandFiles (C:\Users\sakthivelbn\AppData\Roaming\npm\node_modules\pkg\lib-es5\walker.js:152:9)
    at Walker._callee$ (C:\Users\sakthivelbn\AppData\Roaming\npm\node_modules\pkg\lib-es5\walker.js:215:27)
    at tryCatch (C:\Users\sakthivelbn\AppData\Roaming\npm\node_modules\pkg\node_modules\regenerator-runtime\runtime.js:62:40)

**Comment by rytai** [comment]
I have the same error:

> Error! TypeError: Expected `cwd` to be of type `string` but received type `undefined`
    at module.exports.sync (/home/userr/.local/lib/node_modules/pkg/node_modules/dir-glob/index.js:56:9)
    at globDirs (/home/userr/.local/lib/node_modules/pkg/node_modules/globby/index.js:58:9)
    at getPattern (/home/userr/.local/lib/node_modules/pkg/node_modules/globby/index.js:61:64)
    at globTasks.reduce (/home/userr/.local/lib/node_modules/pkg/node_modules/globby/index.js:107:19)
    at Array.reduce (<anonymous>)
    at Function.module.exports.sync (/home/userr/.local/lib/node_modules/pkg/node_modules/globby/index.js:106:26)
    at collect (/home/userr/.local/lib/node_modules/pkg/lib-es5/walker.js:145:27)
    at expandFiles (/home/userr/.local/lib/node_modules/pkg/lib-es5/walker.js:152:9)
    at Walker._callee$ (/home/userr/.local/lib/node_modules/pkg/lib-es5/walker.js:215:27)
    at tryCatch (/home/userr/.local/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:62:40)

**Comment by Controlhaus** [comment]
Also same issue.  
Attempted to downgrade with  
`npm install -g pkg@4.3.4`  
but was unable to downgrade.  

`> pkg@4.3.5
> Error! TypeError: Expected `cwd` to be of type `string` but received type `undefined`
    at module.exports.sync (/usr/lib/node_modules/pkg/node_modules/dir-glob/index.js:56:9)
    at globDirs (/usr/lib/node_modules/pkg/node_modules/globby/index.js:58:9)
    at getPattern (/usr/lib/node_modules/pkg/node_modules/globby/index.js:61:64)
    at globTasks.reduce (/usr/lib/node_modules/pkg/node_modules/globby/index.js:107:19)
    at Array.reduce (<anonymous>)
    at Function.module.exports.sync (/usr/lib/node_modules/pkg/node_modules/globby/index.js:106:26)
    at collect (/usr/lib/node_modules/pkg/lib-es5/walker.js:145:27)
    at expandFiles (/usr/lib/node_modules/pkg/lib-es5/walker.js:152:9)
    at Walker._callee$ (/usr/lib/node_modules/pkg/lib-es5/walker.js:375:25)
    at tryCatch (/usr/lib/node_modules/pkg/node_modules/regenerator-runtime/runtime.js:62:40)`

**Comment by Jullekungfu** [comment]
#603

**Comment by Controlhaus** [comment]
`npm install -g https://github.com/randallknutson/pkg.git#build`  
and a reboot worked for me

**Comment by igorklopov** [comment]
Fixed in `pkg@4.3.6`. Thanks!
