### ISSUE TITLE
Executable still needs modules

### ISSUE THREAD

**Issue by Thomas-Brouwers** [zeit/pkg#613]
Hello,

The executable I generated gives the following error on startup:

pkg/prelude/bootstrap.js:1178
      throw error;
      ^

Error: The gRPC binary module was not installed. This may be fixed by running "npm rebuild"
Original error: Cannot find module 'D:\snapshot\BROT2\node_modules\grpc\src\node\extension_binary\node-v64-win32-x64-unk
nown\grpc_node.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Object.<anonymous> (D:\snapshot\BROT2\node_modules\grpc\src\grpc_extension.js:43:17)
    at Module._compile (pkg/prelude/bootstrap.js:1254:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:711:10)
    at Module.load (internal/modules/cjs/loader.js:610:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:549:12)
    at Function.Module._load (internal/modules/cjs/loader.js:541:3)
    at Module.require (internal/modules/cjs/loader.js:648:17)
    at Module.require (pkg/prelude/bootstrap.js:1159:31)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (D:\snapshot\BROT2\node_modules\grpc\src\client_interceptors.js:145:12)

I want to be able to run it on a pc that doesn't have any of the modules installed. I tried adding it in a require call and in package.json but that doesn't seem to work.

**Comment by mbreedlove** [comment]
Packaging native add-ons has not been solved yet.

https://github.com/zeit/pkg#native-addons

**Comment by varad11** [comment]
I am facing the same issue.
