### ISSUE TITLE
[ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string

### ISSUE THREAD

**Issue by pcnate** [zeit/pkg#615]
I have encountered the following when trying to script this within js. My current work around is to use child_process.exec to call it.

```
[nodemon] starting `node .\bin\build-app.js`
> pkg@4.3.5
(node:17416) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at getPath (D:\github\test\node_modules\dir-glob\index.js:6:41)
    at globs.concat.map.x (D:\github\test\node_modules\dir-glob\index.js:47:59)
    at Array.map (<anonymous>)
    at module.exports.sync (D:\github\test\node_modules\dir-glob\index.js:47:33)
    at globDirs (D:\github\test\node_modules\globby\index.js:58:9)
    at getPattern (D:\github\test\node_modules\globby\index.js:61:64)
    at globTasks.reduce (D:\github\test\node_modules\globby\index.js:107:19)
    at Array.reduce (<anonymous>)
(node:17416) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:17416) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

As per the [README](https://github.com/zeit/pkg#api), I am calling pkg as follows from within an async function.
```
await exec([ 'server.js', '--target', 'node10-win-x64', '--output', path.join( 'dist', 'server-x64.exe' ) ]);
```

My current dependency list is as follows:
```
  "dependencies": {
    "bcrypt": "3.0.2",
    "body-parser": "^1.18.3",
    "cors": "^2.8.5",
    "dotenv": "^6.0.0",
    "express": "^4.16.3",
    "express-jwt": "^5.3.1",
    "jsonwebtoken": "^8.3.0",
    "morgan": "^1.9.1",
    "mssql": "^4.1.0",
    "reload": "^2.3.1",
    "request": "^2.87.0",
    "socket.io": "^2.1.1",
    "sqlssb": "0.0.2"
  },
  "devDependencies": {
    "npm-nomaster-commits": "*",
    "pkg": "^4.3.5"
  },
```

And my node/npm versions
```
PS D:\github\test> node -v
v10.13.0
PS D:\github\test> npm -v
6.5.0
```

Potentially related issues
#544
#487

**Comment by pcnate** [comment]
Seems to be related to expressjs

**Comment by pcnate** [comment]
this only seems to happen when running it via an npm script. I cannot explain why

**Comment by pcnate** [comment]
version 4.3.7 seems to be working after uninstalling pkg globally and locally and then installing the latest
