### ISSUE TITLE
MFC Recorder (windows mfc2.exe error)

### ISSUE THREAD

**Issue by horacio9a** [zeit/pkg#652]
When i start mfc2.exe on win7 receive this error:

[08:31:26] [Server listening on: [0.0.0.0:8888]
[2019/03/24 - 08:31:27] >>> Connecting to MyFreeCams chat server [xchat85]
[08:31:28][Error: Command failed: "C:\nm-mfc2\mfc2.exe" -e "setTimeout(function () { return true; }, 2000);"
internal/modules/cjs/loader.js:594
    throw err;
    ^

Error: Cannot find module '-e'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:592:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1278:46)
    at Function.Module._load (internal/modules/cjs/loader.js:518:25)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1307:12)
    at startup (internal/bootstrap/node.js:274:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:608:3)

Any sugestion?

Used package.json:

{
  "name": "mfc2",
  "license": "ISC",
  "bin": "main.js",
  "pkg": {
      "scripts": ["main.js"],
      "assets": ["index.html","favicon.ico"],
      "targets":["node10"]
	  }
}

This error is only for MFC Recorder v.3.0.6 who uses MFCAuto, I haven't this problem with v.1.0.7 who uses WebSocket

**Comment by horacio9a** [comment]
Successfully resolved.
The problem was the 'system-sleep' module which I removed now.
