### ISSUE TITLE
pkg issue in running with native addons on Linux

### ISSUE THREAD

**Issue by varad11** [zeit/pkg#665]
I am using google-gax module and it has grpc_node.node native addon.
I have placed this addon at the root level with my executable.

On windows when I run my executable everything works fine.

But when I run the linux build on Linux (x86_64) it gives me following error:

`Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v57-linux-x64-glibc\nFound: [node-v57-win32-x64-unknown]\nThis problem can often be fixed by running 
\"npm rebuild\" on the current system\nOriginal error: /home/ec2-user/project/demo/grpc_node.node: invalid ELF header",
  "stack": "Error: Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v57-linux-x64-glibc\nFound: [node-v57-win32-x64-unknown]\n
  This problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: /home/ec2-user/project/demo/grpc_node.node: invalid ELF header\n    
  at Object.<anonymous> (/snapshot/project/node_modules/grpc/src/grpc_extension.js:53:17)\n ",
`

I tried doing "npm rebuild" but it did not solve the issue.

I ran following command: 
`pkg  . -t node8-linux -d`

Thanks for this amazing module.

**Comment by varad11** [comment]
> I am using google-gax module and it has grpc_node.node native addon.
> I have placed this addon at the root level with my executable.
> 
> On windows when I run my executable everything works fine.
> 
> But when I run the linux build on Linux (x86_64) it gives me following error:
> 
> `Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v57-linux-x64-glibc\nFound: [node-v57-win32-x64-unknown]\nThis problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: /home/ec2-user/project/demo/grpc_node.node: invalid ELF header", "stack": "Error: Failed to load gRPC binary module because it was not installed for the current system\nExpected directory: node-v57-linux-x64-glibc\nFound: [node-v57-win32-x64-unknown]\n This problem can often be fixed by running \"npm rebuild\" on the current system\nOriginal error: /home/ec2-user/project/demo/grpc_node.node: invalid ELF header\n at Object.<anonymous> (/snapshot/project/node_modules/grpc/src/grpc_extension.js:53:17)\n ", `
> 
> I tried doing "npm rebuild" but it did not solve the issue.
> 
> I ran following command:
> `pkg . -t node8-linux -d`
> 
> Thanks for this amazing module.

**Comment by varad11** [comment]
grpc_node.node is different for different platforms. Fixed by creating one for linux.
But file names are same between all platform i.e. for Linux it is "node-v57-linux-x64-glibc/grpc_node.node" and for windows "node-v57-win32-x64-unknown/grpc_node.node".

How to place these native addons inside different folder at root level with executables so that based on the current platform it picks up the valid one?
