### ISSUE TITLE
Cannot find module in rethinkdb

### ISSUE THREAD

**Issue by AidanWright** [zeit/pkg#738]
when running rethinkdbdash with:
```js
  const r = require('rethinkdbdash')({
    db: name,
    servers: [{
      host: 'localhost',
      port: 28015
    }]
  });
```
or
```js
  const rethink = require('rethinkdbdash');
  const r = rethink({
    db: name,
    servers: [{
      host: 'localhost',
      port: 28015
    }]
  });
```
it packages successfully but I cannot run index.exe. it produces the following error:
```
(node:4348) UnhandledPromiseRejectionWarning: Error: Cannot find module 'C:\snapshot\DatabaseTest\node_modules\rethinkdbdash\lib/helper.js'
Require stack:
- C:\snapshot\DatabaseTest\node_modules\rethinkdbdash\lib\index.js
- C:\snapshot\DatabaseTest\index.js
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:608:15)
    at Function.Module._resolveFilename (pkg/prelude/bootstrap.js:1287:46)
    at Function.Module._load (internal/modules/cjs/loader.js:524:27)
    at Module.require (internal/modules/cjs/loader.js:664:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:16:16)
    at Object.<anonymous> (C:\snapshot\DatabaseTest\node_modules\rethinkdbdash\lib\index.js:3:14)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:768:10)
    at Module.load (internal/modules/cjs/loader.js:626:32)
    at Function.Module._load (internal/modules/cjs/loader.js:553:12)
    at Module.require (internal/modules/cjs/loader.js:664:19)
    at Module.require (pkg/prelude/bootstrap.js:1166:31)
    at require (internal/modules/cjs/helpers.js:16:16)
    at main (C:\snapshot\DatabaseTest\index.js:0:0)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
(node:4348) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4348) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
The official rethinkdb JavaScript driver works fine but I would prefer I didn't have to resort to that.
I have a feeling it has to do with executing the module but I have no clue where to go after that.

Thanks

**Comment by AidanWright** [comment]
Fixed it by adding
```json
"bin": "index.js",
"pkg": {
    "scripts": ["node_modules/rethinkdbdash/lib/*.js"]
 }
```
to package.json. Then I packaged with `pkg .` from the root of the project. I feel really dumb right about know
