### ISSUE TITLE
Not working with bull

### ISSUE THREAD

**Issue by quaj** [zeit/pkg#752]
I am getting this error when place bull to my source
Any reference?

```
(node:68192) UnhandledPromiseRejectionWarning: TypeError: queue.client.updateDelaySet is not a function
    at Object.updateDelaySet (/snapshot/queue-3g/node_modules/bull/lib/scripts.js:345:25)
    at Queue.updateDelayTimer (/snapshot/queue-3g/node_modules/bull/lib/queue.js:819:6)
    at _initializingProcess.isReady.then.then (/snapshot/queue-3g/node_modules/bull/lib/queue.js:343:21)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:68192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either)
(node:68192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, p.
```
Tried delay 5s then connect but not work

Has created [#1424](https://github.com/OptimalBits/bull/issues/1424)

**Comment by quaj** [comment]
fixed, here more info: https://github.com/OptimalBits/bull/issues/1424#issuecomment-521149625
