### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by jbdemonte** [zeit/pkg#76]
Trying to pack this project https://github.com/jbdemonte/Retro-Manager with this commande:

`pkg package.json --options expose-gc --targets node7-linux-armv7 --out-dir build`

I'm getting this error:

FATAL ERROR: Malloced operator new Allocation failed - process out of memory
> Error! Error: /home/pi/.pkg-cache/v1.9/fetched-v7.6.0-linux-armv7 failed with code null
    at ChildProcess.<anonymous> (/usr/lib/node_modules/pkg/lib-es5/producer.js:39:25)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)

**Comment by firrae** [comment]
Can I ask what you are building on? (platform, hardware, os?)

**Comment by jbdemonte** [comment]
On a raspberry

**Comment by igorklopov** [comment]
To be solved by pkg@3.1

**Comment by igorklopov** [comment]
Pkg@4 consumes much less memory at compilation stage. Please try.
