### ISSUE TITLE
Compilation error with buffer.

### ISSUE THREAD

**Issue by Kradre** [zeit/pkg#82]
Error happend in compilation of simple index.js with few functions.
`C:\Users\Kradre\Desktop\mqttBroker>pkg index.js
> Targets not specified. Assuming:
  node4-linux-x64, node4-macos-x64, node4-win-x64
C:\Users\Kradre\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:89
  return Buffer.alloc(padding);
                ^
TypeError: Buffer.alloc is not a function
    at paddingBuffer (C:\Users\Kradre\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:89:17)
    at C:\Users\Kradre\AppData\Roaming\npm\node_modules\pkg\lib-es5\producer.js:25:48
    at MultiStream._next (C:\Users\Kradre\AppData\Roaming\npm\node_modules\pkg\node_modules\multistream\index.js:81:27)
    at ReadStream.onEnd (C:\Users\Kradre\AppData\Roaming\npm\node_modules\pkg\node_modules\multistream\index.js:119:10)
    at ReadStream.g (events.js:260:16)
    at emitNone (events.js:72:20)
    at ReadStream.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:913:12)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)`

**Comment by igorklopov** [comment]
Please upgrade your node.js version to 4.5.0 or higher.
