### ISSUE TITLE
TypeError when using linvodb3

### ISSUE THREAD

**Issue by serra82** [zeit/pkg#825]
I'm using pkg@4.4.2, I have this error using linvodb3:
```
serra82@bee-xubuntu:~/test/net$ ./db-linux 

pkg/prelude/bootstrap.js:1261
      return wrapper.apply(this.exports, args);
                     ^

TypeError: object is not a function
    at Function.Model.initStore (/snapshot/net/node_modules/linvodb3/lib/model.js:0:0)
    at new Model (/snapshot/net/node_modules/linvodb3/lib/model.js:0:0)
    at module.exports (/snapshot/net/app/routes.js:0:0)
    at Object.<anonymous> (/snapshot/net/server.js:0:0)
    at Module._compile (pkg/prelude/bootstrap.js:1261:22)
    at Object.Module._extensions..js (module.js:662:10)
    at Module.load (module.js:564:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Function.Module.runMain (pkg/prelude/bootstrap.js:1316:12)
```
How can I resolve the problem?

**Comment by serra82** [comment]
the problem in lib/model.js is because leveldown = require('leveldown') is inside try...catch.
Now I have another issue that seems to be linked to #758

**Comment by serra82** [comment]
I added "assets": [ "node_modules/leveldown/**/*" ] in package.json and I copied node.napi.node in the same directory of binary
