### ISSUE TITLE
Error! 404 Not Found -> fetching Node.js binaries; Cannot find NASM

### ISSUE THREAD

**Issue by TS22082** [zeit/pkg#878]
The dev environments should be the same on my laptop and desktop but for some reason my laptop can package the app and my desktop cant. Python2 is not installed on either device. 

Also- When I package it on my laptop it doesn't need to connect to github it just packages it really quick. 

Anyone know how to solve this?

```
$ pkg package.json --target win
> pkg@4.4.5
> Fetching base Node.js binaries to PKG_CACHE_PATH

> Error! 404 Not Found
  https://github.com/zeit/pkg-fetch/releases/download/v2.6/uploaded-v2.6-node-v12.16.1-win-x64
> Asset not found by direct link:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.16.1-win-x64"}
> Not found in GitHub releases:
  {"tag":"v2.6","name":"uploaded-v2.6-node-v12.16.1-win-x64"}
> Building base binary from source:
  built-v12.16.1-win-x64
> Cloning Node.js repository from GitHub...

> Checking out v12.16.1
> Applying patches
> Compiling Node.js from sources...
Looking for Python
Python found in C:\Users\GeekCentric\AppData\Local\Programs\Python\Python38-32\\python.exe
WARNING: Python 3 is not yet fully supported, to avoid issues Python 2 should be installed.
Looking for NASM
Could not find NASM, install it or build with openssl-no-asm. See BUILDING.md.

> Error! Error: cmd failed with code 1
    at ChildProcess.<anonymous> (C:\Users\GeekCentric\AppData\Roaming\npm\node_modules\pkg\node_modules\pkg-fetch\lib-es5\spawn.js:68:23)
    at ChildProcess.emit (events.js:323:22)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)

```

**Comment by TS22082** [comment]
I fixed by uninstalling pkg, then reinstalling again.

```
npm uninstall -g pkg
npm install -g pkg
```
