### ISSUE TITLE
The specified module could not be found. 

### ISSUE THREAD

**Issue by ITS-NIGHTOWL** [zeit/pkg#894]
Running my compiled package on my windows 10 desktop works as expected, but when I run it on my laptop, I get this issue:
 ```javascript
innerError Error: The specified module could not be found.
\\?\C:\Users\itsre\Desktop\installer\pty.node
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1206:18)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at Module.require (pkg/prelude/bootstrap.js:1225:31)
    at require (internal/modules/cjs/helpers.js:77:18)
    at new WindowsPtyAgent (C:\snapshot\cssource-installerv2\node_modules\node-pty\lib\windowsPtyAgent.js:56:40)
    at new WindowsTerminal (C:\snapshot\cssource-installerv2\node_modules\node-pty\lib\windowsTerminal.js:49:24)
× Error: Error: The specified module could not be found.
\\?\C:\Users\itsre\Desktop\installer\pty.node.
```
I checked the directory of my compiled package, and `pty.node` is in fact in `C:\Users\itsre\Desktop\installer\pty.node`, so I'm extremely confused

**Comment by ITS-NIGHTOWL** [comment]
Figured out the issue, it was due to my exe directory missing a DLL pty.node relies on.

**Comment by Kenhuey** [comment]
> Figured out the issue, it was due to my exe directory missing a DLL pty.node relies on.

Which DLL?
